# Generated by Django 5.1.1 on 2024-09-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', help_text='Avatar', upload_to='user/images/'),
        ),
    ]
